python tools/analysis_tools/benchmark.py \
configs/roadformer_cityscapes/befenhance_fusion_convnext-b_cityscapes-512x1024.py \
work_dirs/befenhance_fusion_convnext-b_cityscapes-512x1024/best_mIoU_epoch_24.pth